Modulo para filtrado de csv en tablas con una variable
PyAr/OpenLex pull request #26
Opened 2021-04-12 07:51 UTC by Juerodriguez

Cree este script para filtrar los datos de un csv

2021-04-13 01:53 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +def filter(file_csv,ent_column):
filter es un `builtin` de python, te recomiendo cambiar el nombre. Por ejemplo `filter_csv` o algo siml

2021-04-13 01:53 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +def filter(file_csv,ent_column):
También debería haber un espacio, entre los argumentos, así:

`def filter(file_csv, ent_column)`

Estos "tips" de estilo lo podes encontrar en [PEP8](https://www.python.org/dev/peps/pep-0008/)

2021-04-23 01:20 UTC, Juerodriguez commented
> Cree este script para filtrar los datos de un csv al cargar las tablas de instancias, fueros, jurisdicción que contienen una columna.
> La creación del csv es un éxito, pero aun resta ver porque no recibe los csv el OpenLex.

He estado investigando la razon por la cual no importa los archivos csv y es que existe un error en el metodo "import_from_csv_file" el cual se encuentra en la web2py, archivo web2py/gluon/packages/dal/pydal/objects.py, al parecer en la migracion de codigo hubo un error. La issue es https://github.com/web2py/web2py/issues/2015 

He probado esta solucion en https://groups.google.com/g/web2py/c/t2SEQC9o-ic/m/WiaVzcjsGwAJ y con esto ya me permite importar los csv.

2021-05-29 19:54 UTC, marian-vignau requested changes

2021-05-29 19:54 UTC, marian-vignau commented on modules/filtro_carga_csv/filtro.py
> +            if i == 0:
Esta estructura podrias simplificarla utilizando DictReader
https://docs.python.org/2.7/library/csv.html?highlight=csv#csv.DictReader

2021-05-29 19:54 UTC, marian-vignau commented on modules/filtro_carga_csv/filtro.py
> +        for i,key in enumerate(key_data):
Para esto no necesitas hacer enumerate, ya que la variable i no la usas luego.
Incluso, podrias usar list comprehension, como aca
`b = [[x] for x in a]`

2021-05-29 19:54 UTC, marian-vignau commented on modules/filtro_carga_csv/requirements.txt
> +argparse
requirements.txt solamente menciona paquetes que no son de la biblioteca standard.

2021-05-29 19:54 UTC, marian-vignau commented on modules/filtro_carga_csv/requirements.txt
> +
no agregues ninguna, pues todas son standard

2021-06-12 20:55 UTC, closed without merging