CSV filtering module
PyAr/OpenLex pull request #31
Opened 2021-06-12 20:55 UTC by Juerodriguez

## Summary

Create this script to filter the data from a csv by loading the instance, charter, jurisdiction tables that contain a column.
The creation of the csv is a success, but it remains to be seen why OpenLex does not receive the csv.

## Checklist

- [ ] Variable, methods, funtions and comments
- [ ] Logic
- [ ]Python code with PEP8
- [ ] Tests with Playwright
- [ ] Revisores asignados (pares & al menos 1 mentor)

## Screenshots

(Quick views, image png, gif  and/or video from Playwright)

2021-06-12 21:23 UTC, eamanu requested changes

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +data = []
se suele usar mayusculas para virables globales

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    global data
sin `global` no funciona?

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    with open(file_csv, newline = '') as File:
`File` debería estar en minuscula para seguir pep8

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    with open(file_csv, newline = '') as File:
igualmente file es una palabra reservada.. deberías pensar en otra variable

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +            data.append(file[ent_column])
podrías usar list comprehension https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions
`data = [file[eng_column] for file in input_data]`

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    parser.add_argument("file_csv", help = "Archivo de entrada csv")
```suggestion
    parser.add_argument("file_csv", help="Archivo de entrada csv")
```

2021-06-12 21:23 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    parser.add_argument("out_csv", help = "Archivo csv de salida")
```suggestion
    parser.add_argument("ent_column", help="Nombre de columna de jurisdicciones")
    parser.add_argument("out_csv", help="Archivo csv de salida")
```

2021-06-12 21:38 UTC, Juerodriguez commented on modules/filtro_carga_csv/filtro.py
> +    global data
Tengo que modificar eso ya que la unica variable global era data_in_column.
La cual no funciona sin llamarla en global

2021-06-13 00:05 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    global data
Entonces dejalo como está.

2021-06-13 00:08 UTC, eamanu commented
Me parece más indicado colocar este script en alguna carpeta llamada "scripts", no?

cc:  @marian-vignau

2021-06-20 03:13 UTC, eamanu requested changes
Please add some unittests

2021-06-20 03:13 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    global data_in_column
seems that this isn't longer need?

2021-06-25 12:52 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    global data_in_column
ping @Juerodriguez

2021-06-25 13:52 UTC, Juerodriguez commented on modules/filtro_carga_csv/filtro.py
> +    global data_in_column
```suggestion
    global DATA_IN_COLUMN
```
Deberia quedar asi

2021-06-30 02:27 UTC, eamanu approved these changes

2021-06-30 02:27 UTC, eamanu commented on modules/filtro_carga_csv/filtro.py
> +    file_.close()
file is already closed when `with` clause end. So this `file_.close()` isn't necessary. 
From documentation:
```
It is good practice to use the with keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point. Using with is also much shorter than writing equivalent try-finally blocks...
```
https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files

2021-06-30 11:53 UTC, Juerodriguez commented on modules/filtro_carga_csv/filtro.py
> +    file_.close()
Indeed

2021-06-30 13:05 UTC, Juerodriguez commented on modules/filtro_carga_csv/filtro.py
> +    file_.close()
```suggestion

```

2021-07-03 11:48 UTC, merged