Relate between tables movimiento and agenda, update dashboard/view
PyAr/OpenLex pull request #32
Opened 2021-06-14 15:06 UTC by Juerodriguez

## Resumen

This PR add a relation between the table movimiento and agenda, making it possible to schedule a movement optionally. It also clarifies the timing of urgent tasks 

## Checklist

- [ ] Verified PEP8

## Screenshots

![Captura de pantalla de 2021-06-07 21-35-02](https://user-images.githubusercontent.com/73370773/121914118-5d14aa80-cd08-11eb-8e72-0503ad0944c0.png)

2021-06-20 02:53 UTC, eamanu approved these changes

2021-06-20 02:54 UTC, eamanu requested changes
@Juerodriguez This can be merge? this close any issue?

2021-06-21 17:50 UTC, Juerodriguez commented
> @Juerodriguez This can be merge? this close any issue?

I found one issue when want to create a agenda from movimiento in a link generated by smartgrid.
https://github.com/PyAr/OpenLex/issues/35

2021-07-02 14:33 UTC, Juerodriguez commented
With this last commit https://github.com/PyAr/OpenLex/pull/32/commits/a656ed86c05a55e26230c35c65c3944a7158d07e the agenda link will be hidden from view, so we can merge without issues.

2021-07-02 15:23 UTC, Juerodriguez commented
Taking advantage of the modification of the dashboard view, add in the urgent tasks and overdue tasks section the file field to know which file the task refers to. https://github.com/PyAr/OpenLex/pull/32/commits/f8f4c492648ee6fb642353482a000c35b6f2db64
This implementation was included in my GSoC proposal, I await confirmation to add it. @marian-vignau

2021-07-10 12:37 UTC, eamanu approved these changes

2021-07-10 12:38 UTC, eamanu commented
Amazing work! thanks for the contribution @Juerodriguez

2021-07-10 12:39 UTC, merged