I cleaned databases directory, in order to properly make the testing …
PyAr/OpenLex pull request #39
Opened 2021-06-28 07:09 UTC by matiasdemarchi

…scripts. Then I changed the Readme file, because that example user doesn't exist anymore.

## Resumen

Limpié el directorio de base de datos, con el fin de que los scripts de Playwright que creé, sean aplicables. Del mismo modo, tuve que eliminar del Readme el usuario creado de ejemplo, ya que eso dejó de existir al limpiar el directorio databases, cosa necesaria para que los scripts de testing pudieran funcionar.

## Checklist

- [ ] Variables, funciones y comentarios en Español
- [ ] Corrector ortográfico ok
- [ ] Cdigo Python cumple PEP8
- [X] Cobertura de tests con Playwright
- [X] Revisores asignados (pares & al menos 1 mentor)

2021-06-30 02:38 UTC, eamanu requested changes
The `.pyc` files shouldn't be updloaded to the repository. (But is weird because that files was added to `.gitignore`)

I'm a little confused, why do you remove the .tables files?

Also, please left an explanation on test, about what are you testing

2021-06-30 02:38 UTC, eamanu commented on README.md
> +Puede registrar un usuario de ejemplo, y realizar pruebas con eso
Lo cambiaría por: `Puede registrar un nuevo usuario para realizar pruebas.`

2021-06-30 02:38 UTC, eamanu commented on testeos/agenda-incompleto(ver-issue-atributeerror).py
> +from playwright.sync_api import sync_playwright
Could you leave please a comment about what is testing here, please?

2021-06-30 02:38 UTC, eamanu commented on testeos/calendario-incompleto(ver-issue-agenda).py
> +from playwright.sync_api import sync_playwright
same here about a little explanation about what are you testing.

2021-07-02 19:56 UTC, matiasdemarchi reviewed
I made the changes that you had suggested.

2021-07-02 19:56 UTC, matiasdemarchi commented on testeos/agenda-incompleto(ver-issue-atributeerror).py
> +from playwright.sync_api import sync_playwright
Yes, i will leave a comment in all the playwright scripts.

2021-07-02 19:56 UTC, matiasdemarchi commented on testeos/calendario-incompleto(ver-issue-agenda).py
> +from playwright.sync_api import sync_playwright
Yes, I do.

2021-07-02 19:58 UTC, matiasdemarchi commented
I made the changes that you had suggested to my Pull Request

2021-07-03 11:24 UTC, eamanu requested changes
Algo que no me convence es que borra los `.table` no sé si eso
está bien @marian-vignau @reingart ? Tengo entendido, que por lo 
que me dijo @matiasdemarchi, que el test.sh los borra.

También, fijate que los tests tuyos no se están ejecutando [0], 
eso se debe a que los tests no siguen la conveción [1], deberías 
poner tus tests dentro de la carpeta de `tests/` (no testeo) y deberían
empezar con `test_` algo así: `test_agenda_incompleto_blabla.py`.

Quedan algunos pyc para borrar: `html2text.pyc`, `modules/__init__.pyc` y `__init__.pyc`.


[0] https://github.com/PyAr/OpenLex/runs/2975395180?check_suite_focus=true
[1] https://docs.pytest.org/en/6.2.x/goodpractices.html#conventions-for-python-test-discovery

2021-07-03 11:24 UTC, eamanu commented on testeos/register(obligatorio-primerpaso).py
> +#Testing obligatorio para tener un usuario y contraseña de prueba, para usar los demás scripts.
Los comentarios en python deberían empezar con un espacio, entre el numeral y el comentario en sí, es decir:

`# Testing...`

https://www.python.org/dev/peps/pep-0008/#comments

2021-07-03 11:24 UTC, eamanu commented on testeos/register(obligatorio-primerpaso).py
> +#Testing obligatorio para tener un usuario y contraseña de prueba, para usar los demás scripts.
No es bloqueante pero lo podrías cambiar ? :) (en todos los tests)

2021-07-03 11:24 UTC, eamanu commented on languages/es.py
> +'Request Reset Password': 'Request Reset Password',
```suggestion
'Request Reset Password': 'Solicitar reinicio de contraseña',
```

2021-07-10 12:15 UTC, eamanu commented
@matiasdemarchi existe este error:

```
 ________________ ERROR collecting tests/test_useredit_logout.py ________________
tests/test_useredit_logout.py:201: in <module>
    test_edituser(page)
E   NameError: name 'page' is not defined
- generated html file: file:///home/runner/work/OpenLex/OpenLex/web2py/applications/OpenLex/report.html -
=========================== short test summary info ============================
ERROR tests/test_agenda_incompleto_ver_issue_atributeerror.py - NameError: na...
ERROR tests/test_calendario_incompleto_ver_issue_agenda.py - NameError: name ...
ERROR tests/test_contactos.py - NameError: name 'page' is not defined
ERROR tests/test_expedientes.py - NameError: name 'page' is not defined
ERROR tests/test_forgotten_password.py - NameError: name 'page' is not defined
ERROR tests/test_juzgados_incompleto_ver_issue_tablas.py - NameError: name 'p...
ERROR tests/test_pagina_principal_incompleto_ver_issue_agenda.py - NameError:...
ERROR tests/test_registeruser_obligatorio_primerpaso.py - NameError: name 'pa...
ERROR tests/test_useredit_logout.py - NameError: name 'page' is not defined
!!!!!!!!!!!!!!!!!!! Interrupted: 9 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 9 errors in 0.61s ===============================
```

2021-07-11 11:14 UTC, matiasdemarchi commented
Habiendo solucionado, de mi parte, el tema de los tests, veo que al mergear, el testeo del user se pisa con otro de funcionalidad similar. Habría que ver qué hacer con eso. Aguardo respuesta. Saludos!

2021-07-12 15:41 UTC, eamanu commented on .gitignore
> +venv/
:1st_place_medal:

2021-07-12 15:41 UTC, eamanu commented on .gitignore
> +.venv/
:1st_place_medal:

2021-07-12 15:43 UTC, eamanu approved these changes

2021-07-12 15:49 UTC, eamanu commented
Amazing job @matiasdemarchi.. Thanks for your contribution!

2021-07-12 15:49 UTC, merged