Download zip separated folders
PyAr/OpenLex pull request #41
Opened 2021-07-01 23:15 UTC by Juerodriguez

## Resumen

This PR is next to https://github.com/PyAr/OpenLex/pull/36 still open, in which we began to develop the driver for downloading files and some tests were uploaded.

Here we manage to separate the files according to their respective expedient.

## Checklist

- [ ] Variables, funciones y comentarios en Español
- [ ] Corrector ortográfico ok
- [ ] Cdigo Python cumple PEP8
- [ ] Cobertura de tests con Playwright
- [ ] Revisores asignados (pares & al menos 1 mentor)

## Screenshots

(vista rápida, preferir png, gif animado y/o video de Playwright)

2021-07-11 18:12 UTC, Juerodriguez commented on controllers/expedientes.py
> + -*- coding: utf-8 -*-
```suggestion
 # -*- coding: utf-8 -*-
```

2021-07-11 18:52 UTC, eamanu requested changes

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> + # -*- coding: utf-8 -*-
```suggestion
# -*- coding: utf-8 -*-
```

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    zip_filename = 'Movimiento.zip'
You can use `ZIP_FILENAME`

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    #Obtener ID de expediente y guardarlo en una lista.
pep8
```suggestion
    # Obtener ID de expediente y guardarlo en una lista.
```

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    tempdir7 = tempfile.TemporaryDirectory()
`tempdir7` isn't too descriptive variable name

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    tempdir7 = tempfile.TemporaryDirectory()
temp_dir ?

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    rowA = db(db.movimiento).select()
rowA isn't a descriptive variable name and don't follow the pep8 recommendation.

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +        #Separar archivos por el numero de expediente.
```suggestion
        # Separar archivos por el numero de expediente.
```

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +        rowD = db(db.expediente.id == expedientes).select(db.expediente.numero)
rowB and rowD isn't a descriptive variable name.

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    for expedientes in expediente_lists:
here, expedientes its talk about a single expediente, so, the correct name must be `expediente` (in singular)

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +        expedient = [numero.numero for numero in rowD]
if you fix the `expedientes` name, you should look another name for `expedient` to avoid confusions.

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +                    temparchive.write(file_loc, "upload/" + str(expedient[0]) + "/" + file_name)
an `except` block seems to be missed

2021-07-11 18:52 UTC, eamanu commented on controllers/expedientes.py
> +    result_file = open(output_filename, "w+b")
why don't use with `open(open_filename, '"w+b")` block?

2021-07-12 21:14 UTC, eamanu requested changes

2021-07-12 21:14 UTC, eamanu commented on controllers/expedientes.py
> +        # Separar archivos por el numero de expediente.
Comentario mal indentado

2021-07-12 21:14 UTC, eamanu commented on conftest.py
> +def login(page):
🥇

2021-07-12 21:14 UTC, eamanu commented on controllers/expedientes.py
> +        # return False on success and True on errors
Bad indent  on comment

2021-07-13 09:53 UTC, eamanu approved these changes

2021-07-13 09:53 UTC, eamanu commented
Great job @Juerodriguez. Thanks for your contribution :)

2021-07-13 09:54 UTC, merged