Fix issue 47 in calendar view
PyAr/OpenLex pull request #48
Opened 2021-07-09 14:37 UTC by Juerodriguez

## Summary

With this PR the issue https://github.com/PyAr/OpenLex/issues/47 is fixed, filtering the None data in vencimiento row

## Checklist

- [ ] Variables, funciones y comentarios en Español
- [ ] Corrector ortográfico ok
- [ ] Cdigo Python cumple PEP8
- [ ] Revisores asignados (pares & al menos 1 mentor)

## Screenshots

2021-07-10 12:54 UTC, eamanu requested changes

2021-07-10 12:54 UTC, eamanu commented on controllers/agenda.py
> +    query &= (db.agenda.vencimiento != None)
we should add a restriction in the user side (javascript). Because we are deciding
if use or not the `agenda.vencimiento` column and the user doesn't note that. 

Also, please add tests:
1. one tests trying to get the calendar when `agenda.vencimiento` isn't none,
2. One tests with `agenda.vencimiento` is none, in that way we're testing that your solution work ok.

2021-07-10 20:14 UTC, Juerodriguez commented on controllers/agenda.py
> +    query &= (db.agenda.vencimiento != None)
What we do with this change is not to return the calendar that does not have an expiration date in the calendar.html view, if in this calendar the only thing that is shown is the expiration date, as the data does not exist, the error skips, the Restriction decided not to place it because there will be the case in which it is required to save the agenda field.compliant and not agenda.expiration, case in which the last one will be None

2021-07-16 19:46 UTC, eamanu approved these changes

2021-07-16 19:47 UTC, merged