Added reminder by integrating email
PyAr/OpenLex pull request #59
Opened 2021-07-21 21:08 UTC by Juerodriguez

## Resumen

Issue: https://github.com/PyAr/OpenLex/issues/12
close https://github.com/Juerodriguez/OpenLex/issues/16

This PR adds the option of being able to be reminded by email when a scheduled task is about to be due.

## Checklist

- [x] Variables, funciones y comentarios en Español
- [x] Corrector ortográfico ok
- [x] Cdigo Python cumple PEP8
- [x] Cobertura de tests con Playwright
- [x] Revisores asignados (pares & al menos 1 mentor)

## Screenshots

(vista rápida, preferir png, gif animado y/o video de Playwright)

2021-07-22 12:29 UTC, Juerodriguez commented on cron/crontab
> +* * * * * root *applications/OpenLex_pruebs/cron/check_email.py
```suggestion
0 0 * * * root *applications/OpenLex_pruebs/cron/check_email.py
```

2021-07-24 13:33 UTC, eamanu requested changes

2021-07-24 13:33 UTC, eamanu commented on cron/check_email.py
> +daily_check_email()
ponerlo dentro de un `if __name__ == '__main__'`

2021-07-24 13:33 UTC, eamanu commented on cron/check_email.py
> +    while failed < 4:
Should be a configuration

2021-07-24 13:33 UTC, eamanu commented on cron/check_email.py
> +
Let's create a class to manage this

2021-07-24 13:33 UTC, eamanu commented on models/db_pydoctor.py
> +            zero=T('Elija la frecuencia de la alerta por correo'),  # later we should be able to customize the reminder
better In spanish:

S, O, TW, TH, debería estar en una `Enum`. De esa forma vas a
tener código más legible. Vas a poder poner "Reminder.no_alert" 
lo cual se va a traducir a "O", o directamente podes usar códigos
númericos.

2021-07-24 13:33 UTC, eamanu commented on cron/check_email.py
> +    today = datetime.datetime.now()
take care with timezone. Probably now this is ok, because we're
running this locally, but if we put the system in a cloud, with other
timezone this will get us not expected behavior.

2021-08-09 12:55 UTC, Juerodriguez commented on cron/check_email.py
> +    while failed < 4:
while failed < myconf.take('email_var.error'):

2021-08-09 12:56 UTC, Juerodriguez commented on models/db_pydoctor.py
> +            zero=T('Elija la frecuencia de la alerta por correo'),  # later we should be able to customize the reminder
`Field(
        'recordatorio',
        length=2,
        readable=False,
        requires=IS_IN_SET(
            {
                reminder.no_alert.value: T('Sin alerta'),
                reminder.one_day_before.value: T('1 dia antes'),
                reminder.two_day_before.value: T('2 dias antes'),
                reminder.three_day_before.value: T('3 dias antes')},
            zero=T('Elija la frecuencia de la alerta por correo'), #later we should be able to customize the reminder
            error_message=T('Establezca la frecuencia correcta'))),`

2021-08-09 12:57 UTC, Juerodriguez commented on cron/check_email.py
> +    today = datetime.datetime.now()
This solve with `request.now` from web2py

2021-08-14 19:59 UTC, eamanu approved these changes

2021-08-14 20:00 UTC, eamanu commented
@Juerodriguez Please check the test error.

2021-08-14 20:38 UTC, Juerodriguez commented
> @Juerodriguez Please check the test error.

This error is fixed with this PR https://github.com/PyAr/OpenLex/pull/66

2021-08-14 22:12 UTC, eamanu commented
Great Jonathan @Juerodriguez. Thanks for your contribution

2021-08-14 22:12 UTC, merged